from pptx import Presentation
from pptx.util import Inches

prs = Presentation()

# Slide 1: Title
slide_layout = prs.slide_layouts[0]
slide = prs.slides.add_slide(slide_layout)
title = slide.shapes.title
subtitle = slide.placeholders[1]
title.text = "Anthropic Skills Demo"
subtitle.text = "Generated by python-pptx for analysis"

# Slide 2: Content
slide_layout = prs.slide_layouts[1]
slide = prs.slides.add_slide(slide_layout)
title = slide.shapes.title
content = slide.placeholders[1]
title.text = "Features"
content.text = "1. Analysis\n2. Unpacking\n3. Editing"

# Save
prs.save('sample.pptx')
print("sample.pptx created successfully.")
