# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

ENV MCP_CLIENT_DOCKER=true
# Create app directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies without triggering any unwanted scripts
RUN npm install --ignore-scripts

# Run post-install script for @vscode/ripgrep to download the binary
RUN npm rebuild @vscode/ripgrep

# Copy all source code
COPY . .

# Build the application
RUN npm run build

# Expose port if needed (not specified, so using none)

# Command to run the server
CMD [ "node", "dist/index.js" ]
